### ISSUE TITLE
Can not resolve alias paths

### ISSUE THREAD

**Issue by wrrwrr111** [codemix/deprank#5]
as alias setting in tsconfig.json

"paths": {
      "@/*": [
        "./src/*"
      ]
    }

it reports an error: 
no such file or directory, open '@/pages/form/form.js'

**Comment by adesurirey** [comment]
Same issue here
```shell
npx deprank packages/app/src 

node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, open 'App/reducers/index.mock.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'App/reducers/index.mock.js'
}
```

```jsonc
// tsconfig.json

{
  "compilerOptions": {
    // ...
    "paths": {
      "*": ["packages/app/src/*", "node_modules"],
    }
  },
  // ...
}
```

**Comment by phpnode** [comment]
we use `dependency-cruiser` to resolve dependencies, so this should probably be reported there: https://github.com/sverweij/dependency-cruiser

I'll reopen this issue if it turns out to be a problem on our side

**Comment by RickDT** [comment]
dep-cruiser [supports loading alias maps from a Webpack config](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/faq.md#q-does-this-work-with-webpack-configs-eg-alias-and-modules), but it doesn't look like deprank is picking up dep-cruiser's config file (the `.dependency-cruiser.js` file created if you run `npx depcruise --init`) and passing it in.

Or am I missing something?
